# This is a basic workflow to help you get started with Actions

name: Deploy osu!

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  recompile-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get the last release
      id: nrelease
      uses: pozetroninc/github-action-get-latest-release@v0.4.0      
      with:
        repository: 'ppy/osu'

    - name: Verify number version
      env:
        lv: ${{ steps.nrelease.outputs.release }}
      run: python3 verify-version.py
           
    - name: Download osu!laser apk
      run: wget https://github.com/ppy/osu/releases/download/${{ steps.nrelease.outputs.release }}/sh.ppy.osulazer.apk
    
    - name: Download package for recompile and deploy
      run: |
           sudo apt-get install openjdk-8-jdk-headless
           update-java-alternatives -l
           sudo apt-get install apktool fdroidserver
           pip install -U wheel
           pip install -U PyYAML
        
    - name: Repackage osu!laser for change the version name
      env:
        lv: ${{ steps.nrelease.outputs.release }}
      run: |
           apktool d sh.ppy.osulazer.apk -o "./osu/"
           python3 amhack.py
           apktool build "./osu/"
           ls
